UI/thai.quoc/authentication+status order
comartek/fs-clone-tinwin-customer pull request #10
Opened 2022-09-27 09:04 UTC by thailqcomartek

**Description**

- Authentication Screen:
+ Các màn authentication(login, register, forgot password, OTP, reset Password,....)
+ Lưu ý: Sau khi nhập xong OTP sẽ hiện ra 1 nút tiếp tục để chuyển qua màn tiếp theo.
- Status Order Screen:
+ Các màn trạng thái đơn hàng.
+ Vào phần danh mục Rồi bấm vào dòng chữ Categories ở trên cùng để chuyển sang màn này.
+ Bấm vào nút thanh toán ở màn này để chuyển sang trang trạng thái đơn hàng.
+ Bấm vào nút hủy đơn để modal hủy đơn hiện lên.
+ Bấm vào nút đánh giá để chuyển sang màn đánh giá.
+ bấm vào nút mua lại để chuyển sang màn mua lại
**Git Ticket**

**Testing**

- Manual: Yes
- Automation: No

**Evidence (photos)**

**Extra details**

2022-09-29 03:15 UTC, hoang-comartek commented on src/components/BtnPrimary.tsx
> +      colors={['#FD7D00', '#FEB336']}
màu sắc khai báo ở file riêng.

2022-09-29 03:15 UTC, hoang-comartek commented on src/components/BtnIcon.tsx
> +      colors={['#FD7D00', '#FEB336']}
màu sắc khai báo ở file riêng.

2022-09-29 03:17 UTC, hoang-comartek commented on src/components/account/AccountHeader.tsx
> +      colors={['#FD7D00', '#FEB336']}
common color

2022-09-29 03:20 UTC, hoang-comartek commented on src/components/account/AccountInfo.tsx
> +        onPress={() => navigation.navigate('ChangeInfo')}>
hạn chế dùng inline function
```suggestion
const  onChangeInfo = () => {
navigation.navigate('ChangeInfo')
};
        onPress={onChangeInfo}>
```

2022-09-29 03:30 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +  console.log(props);
xóa log

2022-09-29 03:30 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +    <View style={{zIndex: 1}}>
k dùng style inline

2022-09-29 03:31 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +        <TouchableOpacity onPress={() => setOptionsVisible(!optionsVisible)}>
tương tự với func

2022-09-29 03:31 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +      <View className="h-1.5 bg-gray-100"></View>
```suggestion
      <View className="h-1.5 bg-gray-100" />
```

2022-09-29 03:32 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +            onPress={() => setOptionsVisible(false)}></TouchableOpacity>
tương tự inline func

2022-09-29 03:32 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +            onPress={() => setOptionsVisible(false)}></TouchableOpacity>
```suggestion
          <TouchableOpacity
            className="bg-black-opacity h-full"
            onPress={() => setOptionsVisible(false)} />
```

2022-09-29 03:32 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +            style={{elevation: 10}}>
inline style

2022-09-29 03:33 UTC, hoang-comartek commented on src/components/address/AddressItem.tsx
> +              <TouchableOpacity onPress={() => setOptionsVisible(false)}>
inline func

2022-09-29 03:33 UTC, hoang-comartek commented on src/components/buttons/BtnOrder.tsx
> +  console.log(content);
xóa log

2022-09-29 03:34 UTC, hoang-comartek commented on src/components/buttons/BtnOrder.tsx
> +      colors={['#FD7D00', '#FEB336']}
common color

2022-09-29 03:34 UTC, hoang-comartek commented on src/components/buttons/BtnOrder.tsx
> +          }}>
không dùng inline style

2022-09-29 03:35 UTC, hoang-comartek commented on src/components/buttons/RadioButton.tsx
> +          }}
inline style

2022-09-29 03:36 UTC, hoang-comartek commented on src/components/buttons/SettingsBtn.tsx
> +    <TouchableOpacity onPress={() => navigation.navigate('Settings')}>
viết func ra ngoài

2022-09-29 03:38 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +  };
nên truyền thêm key hoặc type để so sánh, không dùng so sánh label như này (not stable)

2022-09-29 03:38 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +            }}>
inline style

2022-09-29 03:39 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +        }}>
inline style

2022-09-29 03:39 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +        <View style={{flex: 1, height: 1, backgroundColor: '#F9F9F9'}} />
.

2022-09-29 03:39 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +    </View>
xem lại style cả file

2022-09-29 03:41 UTC, hoang-comartek commented on src/components/cards/CardOrder.tsx
> +        />
tương tự, truyền key or type để so sánh, k so sánh title dùng hiển thị

2022-09-29 03:42 UTC, hoang-comartek commented on src/components/modal/ModalAddToCart.tsx
> +        }}
chuyển func ra hàm riêng.
Close modal sao cần hiện alert vậy? Bỏ đi được không?

2022-09-29 03:42 UTC, hoang-comartek commented on src/components/modal/ModalAddToCart.tsx
> +                  }}>
style

2022-09-29 03:42 UTC, hoang-comartek commented on src/components/modal/ModalAddToCart.tsx
> +                  onPress={() => setModalVisible(!modalVisible)}>
func

2022-09-29 03:43 UTC, hoang-comartek commented on src/components/modal/ModalAddToCart.tsx
> +                    color="#000000"></FontAwesomeIcon>
dùng file color

2022-09-29 03:43 UTC, hoang-comartek commented on src/components/modal/ModalAddToCart.tsx
> +                      }}>
xem lại style cả file giúp a

2022-09-29 03:44 UTC, hoang-comartek commented on src/components/modal/modalCancel.tsx
> +export const ModalPoup = ({modalVisible, setModalVisible}) => {
xem lại style inline, func inline file này

2022-09-29 03:47 UTC, hoang-comartek commented on src/components/updateAvatar/UpdateAvatarModal.tsx
> +          }}></TouchableOpacity>
viết func riêng

2022-09-29 03:47 UTC, hoang-comartek commented on src/components/updateAvatar/UpdateAvatarModal.tsx
> +          />
viết func ra ngoài

2022-09-29 03:48 UTC, hoang-comartek commented on src/components/updateAvatar/UpdateAvatarModal.tsx
> +          />
tương tự

2022-09-29 03:52 UTC, hoang-comartek commented on src/navigation/Navigator.tsx
> +          })}
options tương tự nhau, viết 1 const chung thôi

2022-09-29 03:52 UTC, hoang-comartek commented on src/navigation/TabBar.tsx
> +    tabBarActiveTintColor: '#FD7D00',
màu cho vào file const

2022-09-29 03:53 UTC, hoang-comartek commented on src/screens/Authentication/ForgotPassword.tsx
> +            }>
.

2022-09-29 03:53 UTC, hoang-comartek commented on src/screens/Authentication/ForgotPassword.tsx
> +          colors={['#FD7D00', '#FEB336']}
check file color

2022-09-29 03:54 UTC, hoang-comartek commented on src/screens/Authentication/ForgotPassword.tsx
> +                lineHeight: 22,
style

2022-09-29 03:55 UTC, hoang-comartek commented on src/screens/Authentication/FormRegister.tsx
> +const FormRegister: React.FC = () => {
check func, colors, styles

2022-09-29 03:56 UTC, hoang-comartek commented on src/screens/Authentication/FormResetPassword.tsx
> +const FormForgotPassword: React.FC = () => {
tương tự

2022-09-29 03:57 UTC, hoang-comartek commented on src/screens/Authentication/Login.tsx
> +          style={{
tương tự, review lại file

2022-09-29 03:57 UTC, hoang-comartek commented on src/screens/Authentication/LoginWithSMS.tsx
> +            <Text
tương tự

2022-09-29 03:58 UTC, hoang-comartek commented on src/screens/Authentication/ModalAuthen.tsx
> +          Alert.alert('Modal has been closed.');
có cần alert khi close không nhỉ?

2022-09-29 03:58 UTC, hoang-comartek commented on src/screens/Authentication/ModalAuthen.tsx
> +              style={{
review lại style inline

2022-09-29 03:58 UTC, hoang-comartek commented on src/screens/Authentication/ModalAuthen.tsx
> +            <TouchableOpacity onPress={() => setModalVisible(!modalVisible)}>
func inline

2022-09-29 04:00 UTC, hoang-comartek commented on src/screens/Authentication/OTPAuthen.tsx
> +  };
không dùng title để so sánh

2022-09-29 04:01 UTC, hoang-comartek commented on src/screens/Authentication/OTPAuthen.tsx
> +          style={{
xem lại style, color file này

2022-09-29 04:02 UTC, hoang-comartek commented on src/screens/Authentication/Register.tsx
> +        style={{
tương tự

2022-09-29 04:05 UTC, hoang-comartek commented on src/screens/StatusOrder/DetailOrder.tsx
> +          </View>
check style, func, color trong file

2022-09-29 04:05 UTC, hoang-comartek commented on src/screens/StatusOrder/ReviewScreen.tsx
> +  );
xem lại file

2022-10-03 09:30 UTC, thailqcomartek commented on src/components/account/AccountHeader.tsx
> +      colors={['#FD7D00', '#FEB336']}
Phần này của bạn long

2022-10-03 10:21 UTC, phuongna-comartek requested changes
Check lại những chỗ chưa được

2022-10-03 10:21 UTC, phuongna-comartek commented on src/components/cards/CardOrder.tsx
> +        style={{
vẫn còn

2022-10-03 10:21 UTC, phuongna-comartek commented on src/screens/StatusOrder/ReviewScreen.tsx
> +                borderColor: choose === 1 ? '#FC832D' : '#F3F4F6',
color?

2022-10-03 10:21 UTC, phuongna-comartek commented on src/screens/StatusOrder/ReviewScreen.tsx
> +              style={{
.

2022-10-03 10:21 UTC, phuongna-comartek commented on src/screens/notification/NotificationScreen.tsx
> +        style={{backgroundColor: '#00000005', display: bool ? 'flex' : 'none'}}>
.

2022-10-04 07:14 UTC, phuongna-comartek approved these changes

2022-10-04 07:14 UTC, merged