UI/long.pham/cart
comartek/fs-clone-tinwin-customer pull request #14
Opened 2022-09-28 10:29 UTC by longpq51

**Description**

Làm giao diện giỏ hàng, chọn địa chỉ
Sửa Product Detail

**Git Ticket**

**Testing**

- Manual: Yes
- Automation: No

**Evidence (photos)**

![Screenshot_1664359726](https://user-images.githubusercontent.com/111268297/192756218-05e2ee89-0f89-48a1-afe5-1e43b1b1070d.png)

![Screenshot_1664359792](https://user-images.githubusercontent.com/111268297/192756426-b2dee8f8-86dc-4bc2-800a-e2787908707e.png)

![Screenshot_1664359819](https://user-images.githubusercontent.com/111268297/192756596-b51b378e-39f7-40a3-a6ed-16e961b3bf34.png)
**Extra details**

2022-09-29 07:21 UTC, hoang-comartek commented on src/components/address/AddressContainer.tsx
> +        />
move ra func riêng

2022-09-29 07:22 UTC, hoang-comartek commented on src/components/address/AddressContainer.tsx
> +      getItemCount={data => data.length}
.

2022-09-29 07:24 UTC, hoang-comartek commented on src/components/buttons/GoBackBtn.tsx
> +    <TouchableOpacity className={style} onPress={() => navigation.goBack()}>
func

2022-09-29 07:29 UTC, hoang-comartek requested changes
update comment https://github.com/comartek/fs-clone-tinwin-customer/pull/10#issue-1387395740

2022-09-30 02:25 UTC, hoang-comartek commented on src/components/product/ProductsContainer.tsx
> +      />
tách func

2022-09-30 02:28 UTC, hoang-comartek commented on src/components/productDetail/ProductDetailContainer.tsx
> +      )}
- render logic nên tách ra component khác.
- tách func renderItem

2022-09-30 02:31 UTC, hoang-comartek commented on src/screens/Authentication/ForgotPassword.tsx
> +              }}>
style inline

2022-09-30 02:32 UTC, hoang-comartek commented on src/screens/Authentication/FormRegister.tsx
> +            }}>
tách func, style inline file này

2022-09-30 02:32 UTC, hoang-comartek commented on src/screens/Authentication/Login.tsx
> +              <FontAwesomeIcon icon={faEyeSlash} size={20} color="#AEAEB2" />
tương tự

2022-09-30 02:33 UTC, hoang-comartek commented on src/screens/Authentication/ModalAuthen.tsx
> +                  minWidth: 320,
tương tự file này

2022-09-30 02:33 UTC, hoang-comartek commented on src/screens/Authentication/OTPAuthen.tsx
> +            .map((data, index) => (
file này

2022-09-30 02:34 UTC, hoang-comartek commented on src/screens/Authentication/Register.tsx
> +                Tạo tài khoản
.

2022-09-30 02:35 UTC, hoang-comartek commented on src/screens/categories/FilterScreen.tsx
> +            />
,..,.

2022-09-30 02:36 UTC, hoang-comartek requested changes
update comment

2022-10-03 04:56 UTC, phuongna-comartek approved these changes

2022-10-03 04:59 UTC, phuongna-comartek approved these changes

2022-10-03 05:00 UTC, merged